name: ui_masked_text
description: A declarative Flutter UI widget to safely mask and obfuscate sensitive read-only data (emails, phones, credit cards) preventing shoulder-surfing.
version: 0.0.3
homepage: https://github.com/AlnasHossain/ui_masked_text
repository: https://github.com/AlnasHossain/ui_masked_text
issue_tracker: https://github.com/AlnasHossain/ui_masked_text/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0